# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef69e43f735a16628ea09f6a9b05cc25c414c3bf90e2164bae791f22e37f70d9b0e5f32d06efb45661b4b8fc61615774b9c164efc00f4be2f861082e5b0bb690

test:
  secret_key_base: f57ae5417e189c180a9879985405074bfe186798e4820c8af4be1744974b49bf5e7d252b101ee4f944fc505ce18b23d5a01e3eacc33954efaabe250a96af0b16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
